import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<Toaster
          position="top-right"
					toastOptions={{
            duration : 3000,
						success: {
							style: {
								background: "green",
                color : "white",
                border : "2px solid black",
                fontWeight : "bold"
                
							},
						},
						error: {
							style: {
								background: "red",
                color : "white",
                border : "2px solid black",
                fontWeight : "bold"
							},
						},
					}}
				/>
				{children}
			</body>
		</html>
	);
}
